# This is a basic workflow to help you get started with Actions

name: CryptoPrice Update

# Controls when the workflow will run
on:
  # schedule:
  #   - cron: "0 */2 * * *" #every 2 hours
  
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: checkout repo content
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v4

      - name: setup python

        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python packages

        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # JupyterNOtebook Execution Command
      - name: Run JupyterNotebook execution script
       
        run: jupyter execute crypto_scrape.ipynb
        shell: bash

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.txt
          git add *.csv
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.AZURE_SECRET_TOKEN}}
          branch: master 
     
